name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]


    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Update Toolchain (Run cargo)
      run: cargo

    - uses: Swatinem/rust-cache@v1
    
    - name: Get CMake and Ninja (Windows only)
      if: ${{ matrix.os }} == "windows-latest"
      uses: lukka/get-cmake@v3.21.2
      
    - name: Build
      run: cargo build --verbose --release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.os }}
        path: target/release/EpiRSVk*
